- hosts: dcos-cluster
  remote_user: ec2-user
  become: false

  tasks:
  - name: Fetch DC/OS installer from Bootstrap Node
    get_url:
      url: http://{{ hostvars[groups['bootstrap'][0]].ansible_default_ipv4.address }}/dcos_install.sh
      dest: /tmp/dcos

- hosts: masters
  remote_user: ec2-user
  become: true

  tasks:
  - name: Installation of master nodes
    async: 600
    poll: 0
    shell: bash /tmp/dcos/dcos_install.sh master

- hosts: public-agents
  remote_user: ec2-user
  become: true

  tasks:
  - name: Installation of public agents
    async: 600
    poll: 0
    shell: bash /tmp/dcos/dcos_install.sh slave_public

- hosts: private-agents
  remote_user: ec2-user
  become: true

  tasks:
  - name: Installation of private agents
    async: 600
    poll: 0
    shell: bash /tmp/dcos/dcos_install.sh slave
