---
- hosts: all
  remote_user: centos
  become: true


  tasks:
  - name: Install libselinux-python
    yum: name=libselinux-python state=latest

  - name: Set SELinux to permissive mode
    selinux: state=permissive policy=targeted
